### ISSUE TITLE
Interdependant parameter states?

### ISSUE THREAD

**Issue by jwvanderbeck** [jrossignol/ContractConfigurator#150]
So for TestFlight I have made a new Parameter that basically says "collect X amount of Flight Data for Part Y".  Now in actual use, I want to use this in conjunction with additional parameters that specify under what conditions you can collect the data.  Like planets and biomes, for example.  So I only want the data collected param to tick when the other params are true.

Is there a way to do this? Not sure if I am making sense.

**Comment by jrossignol** [comment]
Yup, it makes sense.  So a few ways, depending on how exactly you want it.
```
PARAMETER
{
    name = VesselParameterGroup
    type = VesselParameterGroup

    // Examples of typical child parameters used with VesselParameterGroup
    PARAMETER
    {
        name = ReachState
        type = ReachState

        situation = ORBITING
        biome = Highlands
    }

    PARAMETER
    {
        name = CollectFlightData
        type = CollectFlightData
    }
}
```

This assumes that your class (which I'm calling CollectFlightData in my examples) is a subclass of VesselParameter (although it'll somewhat work even if it isn't).  What VesselParameters + VesselParameterGroup does is locks the group of parameters to a specific vessel.  This prevents having one vessel meet the first parameter, and then have a completely different one meet the second.

Now, depending on how CollectFlightData works, this may be insufficient.  The example above is good for something like science collection as one-time action.

Next option is a slight variation:
```
PARAMETER
{
    name = VesselParameterGroup
    type = VesselParameterGroup

    // Examples of typical child parameters used with VesselParameterGroup
    PARAMETER
    {
        name = ReachState
        type = ReachState

        situation = ORBITING
        biome = Highlands
    }

    PARAMETER
    {
        name = CollectFlightData
        type = CollectFlightData

        completeInSequence = true
    }
}
```

This will prevent the CollectFlightData from making the Incomplete => Complete state transition until all parameters above it are completed (in this case, the ReachState).  This was introduced in 0.7.0, but was broken.  It's fixed in the dev branch, and I'm expecting to release 0.7.1 tonight.

Final note - if you actually want to control some underlying process in the parameter, this alone may be insufficient.  If say flight data collection happens all the time, but you don't want it to actually start until things are ready.  In the above example you could call ReadyToComplete() to know if you are "allowed" to complete.  Broken in 0.7.0 as it is a private method of ContractConfiguratorParameter (made protected in 0.7.1).

Let me know if this answered your question.

**Comment by jwvanderbeck** [comment]
>  If say flight data collection happens all the time, but you don't want it to actually start until things are ready. In the above example you could call ReadyToComplete() to know if you are "allowed" to complete. Broken in 0.7.0 as it is a private method of ContractConfiguratorParameter (made protected in 0.7.1).

data collection occurs over time.  I will check it in OnUpdate and increment the data.  I want to only do that however if the other conditions are currently met.  If the other conditions change to no longer be met I want to stop adding data until such time as the other conditions are again met.

**Comment by jrossignol** [comment]
Yup, then I think you want a VesselParameter, completeInSequence = true, and only collect if ReadyToComplete() returns true.

**Comment by jwvanderbeck** [comment]
Ok sounds good.  I already have it as a subclass of VesselParameter so that's good.  I guess I just need to wait for the update then.

Thanks,

**Comment by jwvanderbeck** [comment]
Ok I think I have the code in place, just need to figure out a proper config and I can test it.

**Comment by jrossignol** [comment]
Closing as resolved.
