### ISSUE TITLE
Undocking DATA node issue

### ISSUE THREAD

**Issue by metl** [jrossignol/ContractConfigurator#176]
When undocking, the undocked vessel retains the targetVessel ID instead of the original vessel.

**Comment by jrossignol** [comment]
The undocking stuff is really complex (because of KSP), and inconsistent in terms of the vessel ids.  I'd need more information to dig into this one (and preferably a save file as well).

**Comment by metl** [comment]
Okay. The core was in place and properly defined as LKOStation. The next contract was to add a power module to LKOStation. Made the dock, then undocked the tug and returned it to Kerbin. CC no longer identified the station as LKOStation. My assumption is it has to do with the way KSP renames vessel when docking/undocking and the name that LKOStation is looking for to be associated with is no longer valid. I have a feeling this may have nothing to do with CC and be entirely on Squad's side. I'll recreate the error and post the save file.

**Comment by metl** [comment]
Here's the save file

https://drive.google.com/file/d/0B_2osj8yAE0XNk1GZTlDWTFONHM/view?usp=sharing

**Comment by jrossignol** [comment]
This stuff is way too complicated, but only because KSP handles docking/undocking in such and akward way and forces it to be.  The issue is that after docking, the two ships become one, and only one vessel id is kept.  When they undock *one* ship keeps the vessel id (pretty consistently the right one) and the other gets a brand new id.  The old code just prayed that the tracked vessel isn't the one that lost and subsequently got a new id.

The new code will:
* Keep track of the root subvessel of the tracked vessel, where the subvessel is a contiguous set of non-docking port and non-decoupler parts.  It hashes some ids of these parts to get a unique identifier.
* When two ships dock, set the tracked vessel to the vessel id that contains the subvessel.
* When ships undock, set the tracked vessel to the vessel id that contains the subvessel.

Actually, that sounds relatively simple.  The complex part is that KSP makes it a PITA and fires events in weird orders and multiple times.  And most are before the ships undock/dock.  Anyway, it's a big hairy mess.  I'll see what I can sort out from the save.

**Comment by metl** [comment]
I had a feeling that was what was going on once I looked at the save file. Thanks for looking into it. It's always amazing the many different ways people find to break things :).. Lol.

**Comment by jrossignol** [comment]
Alright, think I've got this one fixed.  Do me a favour, and grab the development .dll:
https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll

Have a run through with that, preferably on a new save (although it *should* work on an existing save).  Let me know if you're still seeing any issues.  If not, I'll release 0.7.8 in the next couple days.

**Comment by metl** [comment]
I do believe that fixed it. I even checked it with the save file and it does appear to have worked there too
