### ISSUE TITLE
ContractVesselTracker 

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#254]
See https://github.com/severedsolo/KerbinSpaceStation/issues/42 don't know if it can be fixed though

**Comment by severedsolo** [comment]
Gah, messed up the link sorry

**Comment by jrossignol** [comment]
Fixed the link for you. :wink:

**Comment by jrossignol** [comment]
It's hard to say from the user's description.  I think I'd need more specific information if it's believed there's a bug in ContractVesselTracker.  But if he's getting the contract back because of "intentional disassembly" (destroyed?), then that's obviously working as designed.

One option for you is you can have the build KSS contract with a maxCompletions=1, and then have a Rebuild KSS contract that gives no rewards.  That way you still have your failsafe, but it can't be re-spammed as an exploit.  Not sure if that really addresses the issue if there's a bug though.

**Comment by severedsolo** [comment]
I think what he is saying is that if he undocks a part of the station, then redocks elsewhere, the definition is being lost. I've observed similar behaviour when docking to a defined vessel, but have been unable to reproduce reliably enough to file a bug report

**Comment by severedsolo** [comment]
I have no idea how the definition is stored on a vessel, but it seems to me it should be bound to the root part? As long as the root exists, the definition should persist

**Comment by SkyMarshal** [comment]
Sorry the report was terse.  Monday through Wednesday are ridiculously busy for me.  I'll be able to do some testing tonight (GMT-7) and I can clarify any questions you have probably around 20:00 GMT.

**Comment by jrossignol** [comment]
Yeah, but "root part" is not consistent.  If I have two vessels, "A" and "B", and dock them, the root part will be either the original root part of "A" or "B".  When I undock them into the old "A" and "B" vessels, the root parts will not necessarily be the same as they originally were.  I could then hypothetically re-dock and undock and have the root parts change again.

Anyway, here's how the vessel tracking basically works:
- For each vessel, create a list of all "sub-vessels" - a list of contiguous parts that should stay continguous (ie. stops at docking ports and decouplers).  Give this a unique identifier by hashing the flight ids.
- When a vessel is associated, grab the first 'sub-vessel' (which will be the one with the current root part, because that's the best we can do) and use it's identifier.  When undocking events happen, keep the tracked vessel association with the vessel that has that sub-vessel.

The problems are that KSP behaves differently for docking ports, decouplers, and claws; handles loaded and unloaded vessels differently; and a number of other things that make the above more complicated that what I've written.  So I'm almost sure that @SkyMarshal has found some combination where things break down...  which I'll hopefully be able to fix without breaking some other use case.

**Comment by SkyMarshal** [comment]
I'll try to give as many details as I can.  I realized that I have no idea if GMT has daylight savings, so I'll just say I should be free ~6 hours after I submit this comment.

**Comment by severedsolo** [comment]
Yes and no, we go to BST (british summer time) which is GMT+1 - GMT is universal. Anyway off topic.

**Comment by SkyMarshal** [comment]
Aaaand I've got some free time.  Essentially, from your description, @jrossignol, the issue was with how I tended to deploy my space stations.  In this case, I had launched a life support section into an 85km orbit then launched the habitation section separately, with a detachable command module atop so my pilot could return as I hadn't intended to man the station until it was more complete.  I remember being amused when I promptly completed the contract (the hab section met the requirements despite not being docked to the life support section).  Once I had it all docked, I departed and re-entered.... and got another contract for the same thing.  I assume the early completion bound the station to the hab section... whose root part was the pilot-return section.  Additionally, I had left the station not-quite-meeting the requirements (it could hold 4 kerbals, as I intended to extend it with another science lab and a cupola module)... and somehow I ended up getting that same contract three times (total).  I made the issue report as it felt really really unbalanced.

**Comment by SkyMarshal** [comment]
Sorry for the double comment, but (if it is possible, I am unfamiliar with the ContractConfigurator system) having the contract just detect the presence of a valid vessel in orbit of the parent body would probably be best.  I don't know how it'd handle missions regarding the station, though.  Nor multiple compliant vessels.  I already has trouble with valid vessels that don't stick around.  (e.g. accidentially completing a Kerbin station while flying a station to Minmus or whatnot)

**Comment by jrossignol** [comment]
Ah, so from the sound of things, I'd say Contract Configurator is working correctly (or at least, as designed).  For now, I'm going to close this issue and head over to the original one and discuss some ideas for addressing there.  Depending how it goes, we may end up with an enhancement request on CC anyway.
