### ISSUE TITLE
Explicit Deadlines / Options for deadlines

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#273]
The way deadlines are currently set, they:
(a) get multiplied by 0.25 since 1 kerbin day is 6h
(b) get the body weight multiplied in.
Because that's what SetDeadlineDays does.

It would be great if there were an option to disable either a or b (selectively). This could be done by calling SetDeadlineDays(4 x deadline, target) or SetDeadlineDays(deadline, null) or SetDeadlineDays(4 x deadline, null) for a, b, and a&b.
(x is * )

(It took me a fair amount of time to verify that the deadlines weren't shorter because of the game difficulty level, they were shorter because I was on Earth time. Heh.)

**Comment by jrossignol** [comment]
Personally, I never set the deadlines - but in a more controlled environment like RP-0 it probably makes more sense.  I'd totally forgotten that the body multiplier even comes into effect here, which really makes no sense to me (and is missing from my documentation).  So I've fixed it so that the body multiplier no longer gets used for this.

Is that sufficient for this one?  I don't really see a simple/clean way to handle the 6/24 hour day - I'd rather just have you multiply it by 4.

**Comment by NathanKell** [comment]
That's fine, sure. Although I'd ask if possible to have the body multiplier toggleable--for example, an orbital contract with a random target could make use of the body multiplier to allow for longer deadlines for longer transfers.

**Comment by jrossignol** [comment]
How about if I expose the multiplier(s) through expressions instead?  That way you can do:
```
deadline = 10.0 * ContractMultiplier()
```
I'd probably have a multiplier for body, prestige and a contract level one that includes both.

**Comment by NathanKell** [comment]
Yeah, that makes even better sense!

**Comment by jrossignol** [comment]
Done for 1.5.5:
* ContractMultiplier() - Gets the combined multiplier for the contract.
* CelestialBody.Multiplier() - Gets the multiplier for the given body.
* ContractPrestige.Multiplier() - Gets the multiplier for the given prestige level.
