### ISSUE TITLE
Best practices for 1-active-only and for tracking completions, SR/Orbit

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#275]
Moar RP-0 questions!

1. I would like the player to only be able to have one Sounding Rocket contract accepted at any given time, but 2 (low/med or med/high) available if none have been accepted. Do I do this with 2x inverted ActiveContract parameters on each of the three ocntracts, or is there some easier way? Max simultaneous for groups applies to the contract list too.

2. Is there a built in variable for tracking how many times a contract has been completed, or should I add a behavior on contract complete that increments an expression?

3. More generally, I'd like to prevent a player accepting a sounding contract and an orbital contract and doing both. My best thought for now is to require the vessel fulfilling the sounding contract to reenter (situation flyinghigh in order after altitude achieved) and never have achieved orbit. Am I missing an obvious solution?

**Comment by jrossignol** [comment]
1. Hoo boy, you have complicated requirements. :wink: I'd make sure it's clear to the player they can't have more than one active at once... as it'll be a bit jarring the first time otherwise.  Anyway, the way you've said is one of two ways I can think of.  The other way is to use an Expression behaviour to set a flag when the contract is accepted and unset it when it's completed (note that there's two places you have to set it - one for successful completion and one for failed completion).

 If you don't want Low/High to get offered together, the only way I can think of is to put them in a group together, and put Med in another group (a parent group).  The Low/High group would have maxSimultaneous to 1.  The side effect is that you can't be offered Low/Low or High/High.

 1. No - although the CompletedContract and AcceptContract have access to it.  Otherwise if you want to do that, incrementing a variable is your best bet.

 1. Well, if you use an expression to set a variable, you can use that on the orbit ones too to prevent them from accepting both.  But if you want them to be able to "hold" both contracts and only complete one, I can't think of a better solution than what you've suggested.

**Comment by NathanKell** [comment]
1. Heh. The idea is you shouldn't be able to double-dip, i.e. if you're launching a science payload for group x, that means you can't also be launching it to group y's specifications. Though funds are tight enough that I guess it's a low priority to do that, I agree that's not terribly intuitive for (KSP) players.

2. Gotcha.

3. Yeah, it's being able to hold both but not complete both. Ok, I'll do it that way.

Thanks!
