### ISSUE TITLE
Autoaccept contracts and switching to TrackingStation

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#284]
The autoaccept record contracts that RP-0 contains will appear to not always trigger the acceptance of the next record contract on current contract completion; I get the acceptance of the next contract when flying sounding rockets, but when flying crewed missions I have to switch away from flight and return to get the next crewed record to be accepted (and prior record cleared from the contracts list). A forum user reports that they have to leave flight for _any_ record contract to re-up.

Thoughts?

**Comment by jrossignol** [comment]
I have a fairly good guess as to what's going on.  When KSP decides to generate contracts is a bit of a black box, but based on some testing a while back I'm fairly certain it happens on a couple events:
 1. When the player's rep changes
 1. When a ProgressNode is reached
 1. When exiting non-physics timewarp (not 100% sure about this one).
 1. Periodically...  don't believe it's OnUpdate but seems to happen fairly often.
 1. When a contract is completed (95% sure)
In the past, I had some performance issues where KSP was asking for contracts too often and it would bog the system down (because at the time I would check all possibilities to try and generate one, and there were some that were pretty bad for performance).  So I now have the ContractPreLoader ScenarioModule that will pre-generate the contracts using a co-routine (which has a lot of possibly pause-points).  When asked for a contract, it'll pop one off the queue, or if a suitable one isn't ready, it'll try to generate it until a timeout is reached (and oops...  that was supposed to be a longer timeout, but it's using the 10ms from the co-routine - raised #285 to look into that one.)

Anyway, one of two things is happening:
 1. KSP just isn't asking for a contract.  I think that it does whenever a contract completes, so I don't think that's it.
 1. KSP is asking for a contract, and a different one than the one we want is ready.  Or there isn't another ready, but we can't generate ours in time.

So Fixing the timeout may help a little, but I have a better idea.  What I'll do is start treating the autoAccept contracts special.  Whenever the contract pre-loader successfully generates one, it will immediately call ContractSystem.RefreshContracts().  This, plus having some logic to push autoAccept contracts to the top of the queue should be enough to make sure they get generated.

**Comment by NathanKell** [comment]
Awesome!

I guess one other approach would be to just force the acquisition of the contract whenever requirements are met? Or is that contrary to how CC works, period?

**Comment by jrossignol** [comment]
That would be so much simpler - the problem is that it's contrary to how the stock contract system works.  It will request that a contract of a given type be generated, and will calls call that type's default constructor, followed by a couple other methods.  That's the only way to get a contract into the system (as you need it added to a private list of contract in the ContractSystem ScenarioModule).  I'm sure I could try out a few hacks to get it in (add to the private lists via reflection, call the save/load methods and insert my data in between)....  but they're likely to have side effects.

**Comment by NathanKell** [comment]
Yeah. Fair point. If you wanted to go full-bore reflection you could just manually copy what KSP itself does, but that'd be a fair amount of work.

**Comment by jrossignol** [comment]
Fixed for 1.6.4, but found a tangential issue in #288.
