### ISSUE TITLE
Spawning on water causes Kerbals or vessels to reappear at ocean floor sometimes

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#350]
I've noticed that if I set SpawnKerbal to spawn a Kerbal on water (for later rescue), that when I fly in my rescue craft, and the game starts to render the ship or kerbal, that sometimes (more often) the kerbals appear on the surface and then instantly reappear at the bottom of the ocean floor. Less often the vessel does the same. Not sure if its a KSP bug.

See this for a test contract: https://github.com/inigmatus/SSI-Aerospace/blob/master/RescueFishermen.cfg

Fly out with your plane over the survivors, and you sometimes they will drop to the bottom of the ocean.

**Comment by jrossignol** [comment]
I have code to handle that in SpawnVessel, but not SpawnKerbal, so I can fix that.

If you can find a vessel that you're having this issue with, I'll need some assistance.  What I'd need are:
 1. The contract definition that generated it
 1. The vessel file
If it's not 100% reproducible, then instead I'd need:
 1. The VESSEL node from the persistence file before you visit it
 1. The VESSEL node from the persistence file after you visit it and are able to "fix" it (assuming you can).

**Comment by inigmatus** [comment]
See this for a test contract: https://github.com/inigmatus/SSI-Aerospace/blob/master/RescueFishermen.cfg

referenced craft:
https://github.com/inigmatus/SSI-Aerospace/blob/master/Assets/fishingvessel.craft

**Comment by jrossignol** [comment]
I haven't been able to reproduce this one, but I think everything's working correctly and it's KSP that's giving you grief.

Instead of spawning the boat underwater, spawn the Kerbals in the air (a drop of a few meters won't hurt them...  much).

If you want to be really precise, get everything set up correctly in game, and then go look at the values for the vessels (boat + kerbals) in the persistent.sfs.  Use the altitude values you find there to "seed" the values in your contract - hopefully that way when you do it via SpawnVessel/SpawnKerbal, it'll work just right.

**Comment by inigmatus** [comment]
I'll try that and report back.

**Comment by jrossignol** [comment]
Closing this one out - can be reopened if there's a CC issue.
