### ISSUE TITLE
activeUniqueValue doesn't seem to be working.

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#374]
Assuming I'm using this right (after your little explanation a while ago) - I think this should stop KSS from generating more than 1 contract per station at a time - even if they are different contracts.

However, my game has generated two (separate) contracts for my "Kerbin Station" at the same time.

(CC 1.8.3, KSS 3.0.2 - normal playthrough no dev testing).

**Comment by jrossignol** [comment]
Actually, it will check across CONTRACT_TYPE nodes.  I think it's finally time to make a little change to this, as the activeUniqueValue/uniqueValue stuff is just not intuitive.  I'm planning on deprecating those (although I probably will never remove them due to backwards compatibility).  Instead I will introduce the `uniqueCheck` attribute.  It will have the following values:
 * None (the default)
 * CONTRACT_ACTIVE
 * CONTRACT_ALL
 * GROUP_ACTIVE
 * GROUP_ALL
I haven't decided yet whether GROUP_x should mean the parent group or the root group.

**Comment by jrossignol** [comment]
Done for 1.9.0

**Comment by severedsolo** [comment]
Just to check: so for my usage case - I want each station to only ever have one maintenance contract offered at a time, but multiple stations can get a contract at the same time.

So I'd use uniquenessCheck = GROUP_ACTIVE ?

**Comment by jrossignol** [comment]
That is correct.
