### ISSUE TITLE
Any way to unset an experiment?

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#430]
The second, I am not sure that you can do anything about, based on your earlier comments:  Once I run an experiment, it goes green in the contracts window, and is green for all succeeding waypoints.  Note that the "Collect science" line IS white until I run the experiment.  Is there any way (either now or in the future) that you can come up with a way to unset an experiment, say, after it was transmitted?

Here is a thought: Why not check to see if the experiment is storing any data?  So, for example, have a parameter which would set the state of an(all) experiment(s) based on whether they have data?  This way I could use that as the first parameter of my series of experiments

**Comment by jrossignol** [comment]
With the fix to #428, this should no hopefully longer be necessary - the experiment won't get checked until the pre-requisites (ie. the completeInSequence stuff) is met.  Otherwise resetting it would require some expensive code that checks all the science containers in the vessel.

Closing for now, we can re-open this issue if needed though.
