### ISSUE TITLE
Enhancement: Expression Desired: partCountOnLaunch()

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#466]
I need an easier way to code to check when a player attaches via SPH/VAB or docks a vessel such as a buoy or cargo container, and then code a check for when such has been removed from the combined vessel.

The Docking parameter only checks for docking, not attachment in SPH/VAB, and does not handle undocking checking.

My idea is this:

an expression that returns a count of the number of parts a vessel launches with

which can then be used in a in a Part Validation parameter:

PARAMETER
{
    name = PartValidation
    type = PartValidation

    part = barometer

    minCount = partCountOnLaunch() - 1

}

which would check if an installed subassembly that has a barometer, was then at some point undocked from the launched vessel.

PARAMETER
{
    name = PartValidation
    type = PartValidation

    part = barometer

    minCount = partCountOnLaunch() + 1

}

which would check if a launched vessel then docked or was attached to another vesssel that has a barometer.

This is what I could think of. Thoughts?

**Comment by jrossignol** [comment]
Wouldn't work, because all expressions are executed at time of contract generation (with the exception being the Expression behaviour).

If you're trying to detect that the buoy has been launched, I'd do it as a VPG for the buoy (PartValidation, ReachState = Splashed, VisitWaypoint).  Those vessel parameters are all *supposed* to work on non-active vessels - but it hasn't been extensively tested, so if it doesn't then we can work through the bugs.
