### ISSUE TITLE
Any amount in advanceFunds fails contract on acceptance when rewardFunds is negative

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#480]
Trying to create a loan contract. Feel free to test: https://github.com/inigmatus/GAP/blob/master/Economy/SSI-Loan.cfg

Setup:
rewardFunds is negative.

Control:
If advanceFunds is 0, I can accept contract and Timer parameter completes, and negative funds are taken out. - working as designed

Issue 1:
If advanceFunds is greater than 0, contract displays with failureFunds negatively equal to the advanceFunds amount, even if failureFunds is set to 0 in cfg.

Issue 2:
Also, if advanceFunds is greater than 0, accepting contract (even if I manually enter a failureFunds greater than 0) immediately fails the contract, thus ignoring the Timer parameter.

**Comment by jrossignol** [comment]
Issue 1 is a documentation issue, that's how it's meant to work.  Fixed the doco.

Issue 2 is working correctly - the timer is always successful, and counts down until it hits zero and fails the contract.  It works that way so that when other parameters complete, it will not block the contract from completing.  When there are no other parameters, the contract will just complete.

Either use the Duration parameter (which will cause the contract to succeed in X days), or add another hidden parameter that can never be completed if you want it to work with the Timer).
