### ISSUE TITLE
targetBody = AllBodies() throws

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#491]
CC 1.9.7 reports cannot cast from List.

**Comment by jrossignol** [comment]
The problem is that targetBody gets loaded in two places - generically in ParameterFactory as CelestialBody, and in ReachStateFactory as List<CelestialBody>.  It's the base class's parsing of it that is failing.

I can't seem to wrap my head around how I had this working - it might be that I had it under a non-clashing name and then renamed it without properly testing.  Only workaround in the meantime is manually specifying multiple targetBody lines.

**Comment by jrossignol** [comment]
Fixed for next release (not sure if there will be another 1.0.5 release though).
