### ISSUE TITLE
SCANsat returns a 100% coverage while loading inFlight/Planetarium Scene

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#57]
This is a instant success for coverage parameter, only work around would be to set allowStateReset = True. I did a quickfix and ignore straight 100.0 double values while checking the coverage. I'm not sure the coverage could be 100% or ever will only be 99.999999%. I will make a pull request.

**Comment by SimonTheSourcerer** [comment]
I Got about 4 debug messages. Cant remember how long the delay between those Parameter  ckecks are.

**Comment by jrossignol** [comment]
Forgot to link my commit, but have a look at the 0.4_fixes branch (https://github.com/jrossignol/ContractConfigurator/tree/0.4_fixes).  If the fix there works for you I'll make that into the 0.4.3 release.

The fix is as follows:
- Require 2 consecutive successes to consider the parameter completed
- Up the check interval to 5 real seconds
- Add an alternative check that checks every 100 *game* seconds - that way it'll check quicker than every 5 real seconds on high timewarp settings (which if the player is sitting and watching is the most likely scenario.

Let me know if it works for you, and send a pull request if it works but you want to tweak the values.  I haven't actually reproduced the issue - so I don't know for sure that this fix works. :smile:

**Comment by jrossignol** [comment]
Ah there we go - Happy New Year from Canada!   Time to sleep. :sleeping::zzz:

**Comment by SimonTheSourcerer** [comment]
Nice, did some testing, looks like its a proper solution.*approve*

**Comment by jrossignol** [comment]
Released 0.4.3
