### ISSUE TITLE
Interfearence with ScanSAT

### ISSUE THREAD

**Issue by TheFarix** [jrossignol/ContractConfigurator#590]
While conducting a career play, Contract Configurator v1.20.2 prevented the activation of the RADAR scanner. Removing Contract Configurator allowed me to activate the scanner. Other ScanSAT scanners have not been tested to see if there were similar problems.

**Comment by jrossignol** [comment]
This is the toolbar compatibility issue reported on the Toolbar and Contract Configurator threads.  Please raise the issue against SCANsat.

**Comment by TheFarix** [comment]
This has nothing to do with Toolbar. It isn't even installed.

**Comment by ahmedcharles** [comment]
To integrate with the Toolbar mod, other mods need to include the ToolbarWrapper code. There's a bug in that code, which is included in SCANsat, hence why it's a SCANsat/Toolbar bug. Apparently, mods that have the new version of the code break mods which do not have the new version of the code, which is unfortunate.

**Comment by jrossignol** [comment]
> Apparently, mods that have the new version of the code break mods which do not have the new version of the code, which is unfortunate.

This part is false.  See here:
http://forum.kerbalspaceprogram.com/index.php?/topic/150719-contract-configurator-broke-my-mod/

**Comment by ahmedcharles** [comment]
I read that. It doesn't explain what the actually technical issue is, so I (incorrectly) assumed that the reason contract configurator breaks other mods with ToolbarWrapper is because it has the new version of ToolbarWrapper. Given no more information about what actually causes the failure, it's a reasonable assumption. And I did use 'apparently', which suggests I wasn't sure and it was a hypothesis.
