### ISSUE TITLE
Static contract limit methods inaccurate

### ISSUE THREAD

**Issue by DMagic1** [jrossignol/ContractConfigurator#593]
Do these methods still work?

https://github.com/jrossignol/ContractConfigurator/blob/master/source/ContractConfigurator/ContractConfigurator.cs#L482-L504

They don't seem to return accurate values.

**Comment by jrossignol** [comment]
They should - but they now are dependent on game settings, so they are no long accurate until after GameParameters are loaded (not sure how/when you were checking the values before).

**Comment by DMagic1** [comment]
Just looking at the code, and at what I see when I call the contract limits method, for a rep of 0 (ie starting a new game), the max 1 star contracts should be 6. But when I enter the MC building it shows a limit of 2 for each level.

I assume that the display is just showing the minimum of the total contract limit compared to the per level limit. The methods linked to above don't reflect that. I can take that into account on my end, I'm just not entirely sure if that's the intended effect.

**Comment by jrossignol** [comment]
Ah, yes.  There was some user confusion, so I changed the UI to take building limits into account, but never changed that method (I did it directly in the UI classes).  Part of the reason might've been because at the time the static method didn't depend on anything in the current game - but it does now anyway.

If you like I can change it - but I'm fine either way (easier for me not to touch it 😉)

**Comment by DMagic1** [comment]
I already took care of it on my end, so there's probably no need to change it; thought it wouldn't affect me if it were changed.
