### ISSUE TITLE
Falling Kerbals

### ISSUE THREAD

**Issue by Keniamin** [jrossignol/ContractConfigurator#633]
Hello! Can you please comment a problem from https://github.com/Keniamin/KerbinSideGAP/issues/2 ? Not sure if it is really a bug of Contract Configurator, but it would be great if you could check it out. Game log is attached in the linked thread, see from Scene Change at 02:18:11.

**Comment by jrossignol** [comment]
I'll take a closer look at this one.  The description (being on the ground at one point and off the ground at another) makes it sounds like something broke with KSP 1.3.0.

For background, there are two values for landed vessels in the save file - one that is used for unloaded vessels, one for loaded vessels.  Because it's using the loaded value, the Kerbals look to be in the right place, but when their vessel gets loaded, they "jump" to the other location.

**Comment by Keniamin** [comment]
Thanks a lot for watching the issue. To help you I must say that I checked it in v1.2.2, so it is definitely not an effect of v1.3.

**Comment by jrossignol** [comment]
Looks like something in KSP changed around the terrain at KSC (it seems like the KSC model is now treated as real terrain, so the spawn code was spawning them in the air by the same amount KSC was above the "real" ground.

Anyway, fixed for next release.
