### ISSUE TITLE
DATA_EXPAND fails when a Expression Requirement exists

### ISSUE THREAD

**Issue by gyf1214** [jrossignol/ContractConfigurator#653]
1.23.3 on KSP 1.3.1

When there is a Expression Requirement, it says: unexpected child node 'DATA_EXPAND' found, ignored.

**Comment by jrossignol** [comment]
Can you send the full block that's failing so I can have a look and test it
out?

**Comment by gyf1214** [comment]
Figured out somehow. It seems to be some error before the DATA_EXPAND check so according to ContractType.cs:401 DATA_EXPAND is skipped. However, the error message is not printed so the log seems weird.

**Comment by gyf1214** [comment]
The 'title' field of Expression Requirement is required after 1.15.0 but wiki is not updated, plus I simply missed the error message. I recommend that the valid check @ContractType.cs:401 should just return when failed instead of go through the rest of the process to avoid the messy error message. Maybe use Exception instead? Close.

**Comment by jrossignol** [comment]
I added a warning for this case to hopefully make it more obvious what the problem is, as well as correcting the wiki to indicate that title is conditionally mandatory (but mandatory more often than not for the Expression requirement).

If you aren't already, you may want to use the ALT+F10 debug window - that can also be handy in catching these types of issues.
