### ISSUE TITLE
VesselParameterGroup resets when wrapped parameter resets.

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#66]
I think it worked in earlier versions, but is broken now. Occured on the actual master branch. 

Tried:
disableOnStateChange = True
allowStateReset = False

Didn't helped. Prevents from doing contracts with duration. 

Parameter:

	PARAMETER
	{
		name = VesselParameterGroup1
		type = VesselParameterGroup
		
		duration = 20s
		
		title = Do some fine tuning and hover for 20 seconds in air at a maximum speed of 10m/s 
		
		PARAMETER
		{
			name = ReachSpeedEnvelope1
			type = ReachSpeedEnvelope

			// Minimum and maximum speeds, required
			minSpeed = 0.0
			maxSpeed = 10.0
			
			disableOnStateChange = False
			allowStateReset = True
		}
		
		PARAMETER
		{
			name = ReachAltitudeEnvelope1
			type = ReachAltitudeEnvelope

			minAltitude = 2000
			maxAltitude = 2500
			
			disableOnStateChange = False
			allowStateReset = True
		}
	}

**Comment by jrossignol** [comment]
Try this:

	PARAMETER
	{
		name = VesselParameterGroup1
		type = VesselParameterGroup
		
		duration = 20s
        disableOnStateChange = True

		title = Do some fine tuning and hover for 20 seconds in air at a maximum speed of 10m/s 
		
		PARAMETER
		{
			name = ReachSpeedEnvelope1
			type = ReachSpeedEnvelope

			// Minimum and maximum speeds, required
			minSpeed = 0.0
			maxSpeed = 10.0
		}
		
		PARAMETER
		{
			name = ReachAltitudeEnvelope1
			type = ReachAltitudeEnvelope

			minAltitude = 2000
			maxAltitude = 2500
		}
	}

The problem is that I played around with the default values for disableOnStateChange - it ended up that you had to specify it for almost EVERY VesselParameter (as false).  Based on this, I think I will change VesselParameterGroup back (so it defaults to true for that one).

From the Parameters page:

    // When the parameter's state changes to completed or failed, disable
    // the parameter.  Use a value of false if you are trying to make
    // something behave like the Squad part test contract.  Example, if the
    // parameter says you need to be between 1000 and 2000 meters altitude
    // then setting this to false will make the parameter go back to
    // incomplete if you enter and leave the altitude window.
    //
    // Default = <differs per parameter, see detailed documentation below>
    disableOnStateChange = true

One more note - allowStateReset shouldn't be supported via the config files (I didn't think it was).  It's poorly named, but it's a workaround for the fact that I need to be able to keep changing the state of the child VesselParameters (as they are tracked per vessel vs. globally).  I shouldn't have given it an opposite logic to disableOnStateChange. :disappointed: 

Anyway, try that, and I'll change the default as soon as I can.

**Comment by SimonTheSourcerer** [comment]
I tried that. Did not work. Still jumps back from complete after leaving parameters.

VesselParameterGroups sourcecode is a little bit to complex (for me) to jump into it and find the problem. If I had to guess OnParameterStateChange setIncomplete() could be the problem.

**Comment by jrossignol** [comment]
Okay, let me dig into it... Like you said, VesselParameterGroup is too
complex... For me too!

**Comment by jrossignol** [comment]
I changed the default value to True for VesselParameterGroup - still doing some testing though.

**Comment by jrossignol** [comment]
Everything's working the way I expected, so either I didn't reproduce the issue correctly, or there's a misunderstanding on how it's supposed to work, here's the cases I tested, and my expected results:

VPG disableOnStateChange | VP disableOnStateChange | VP resets | VPG resets |
---|---|---|---
True|False|Yes, until duration is exceed, then fixed|Yes, until duration is exceeded|
False|False|Yes, until duration is exceed, then fixed|Yes, even after duration is exceeded|
False|True|Never|Never, because child parameters don't change|
True|True|Never|Never|

Here's my test contract - slight modification to the altitude just to make testing on the launchpad easier:

    CONTRACT_TYPE
    {
        // Unique name of the contract (required)
        name = VPG_Reset

        // Contract text
        title = VPG Reset/State Change Test
        description = A more detailed description of the contract.  This is where you come in.
        synopsis = We want you to do a thing.
        completedMessage = You have done the thing.

        // Target Celestial body - controls where the contract must be completed, has some automated
        // effects on numeric parameters (increasing science, etc.)
        targetBody = Kerbin

        // Contract rewards
        rewardScience = 100.0
        rewardFunds = 100000.0

        PARAMETER
        {
            name = VesselParameterGroup1
            type = VesselParameterGroup

            duration = 20s

            title = Do some fine tuning and hover for 20 seconds in air at a maximum speed of 10m/s 

            PARAMETER
            {
                name = ReachSpeedEnvelope1
                type = ReachSpeedEnvelope

                // Minimum and maximum speeds, required
                minSpeed = 0.0
                maxSpeed = 10.0
            }

            PARAMETER
            {
                name = ReachAltitudeEnvelope1
                type = ReachAltitudeEnvelope

                minAltitude = 0.1
                maxAltitude = 2500
            }
        }

        PARAMETER
        {
            name = PlantFlag1
            type = PlantFlag

            targetBody = Duna
        }
    }

**Comment by SimonTheSourcerer** [comment]
Tested it again today, the old CC version I compiled still didn't work. So did a clean checkout compiled a new version. This one is working. Well looks like I messed up something or so. I'm sorry for wasting time :(

**Comment by jrossignol** [comment]
No worries, it's quite possible I inadvertently broke and fixed it. :p
